directories:
  output: release
  buildResources: build
appId: com.yourname.art-text
productName: 矢量艺术字生成器
win:
  target: nsis
  icon: public/favicon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
files:
  - filter:
      - dist/**/*
      - electron/**/*
electronVersion: 42.0.1
